#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_APT_SOURCES_LIST_CONFIG=${ESB_APT_SOURCES_LIST_CONFIG:-"/etc/apt/sources.list.d/enterprisestoragebox.list"}
ESB_APT_REPOSITORY_URL=${ESB_APT_REPOSITORY_URL:-"http://packages.enterprisestoragebox.org/public"}

mkconf() {
	# Get the distribution name.
	distribution=$(esb_product_info "distribution")

	# Create '/etc/apt/sources.list.d/enterprisestoragebox.list' file
	cat <<EOF > ${ESB_APT_SOURCES_LIST_CONFIG}
deb ${ESB_APT_REPOSITORY_URL} ${distribution} main
# deb http://downloads.sourceforge.net/project/enterprisestoragebox/packages ${distribution} main
EOF

	xmlstarlet sel -t -m "//system/apt/distribution" \
	  -i "proposed = 1" \
		-o "## Uncomment the following line to add software from the proposed repository." -n \
		-o "deb ${ESB_APT_REPOSITORY_URL} ${distribution}-proposed main" -n \
		-o "# deb http://downloads.sourceforge.net/project/enterprisestoragebox/packages ${distribution}-proposed main" -n \
	  -b \
	  -i "partner = 1" \
		-o "## This software is not part of EnterpriSestorageBox, but is offered by third-party" -n \
		-o "## developers as a service to EnterpriSestorageBox users." -n \
		-o "deb ${ESB_APT_REPOSITORY_URL} ${distribution} partner" -n \
		-o "# deb http://downloads.sourceforge.net/project/enterprisestoragebox/packages ${distribution} partner" -n \
	  -b \
	  ${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_APT_SOURCES_LIST_CONFIG}
}

case "$1" in
	mkconf|*)
		mkconf
		;;
esac
