#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://www.korbinian-pauli.de/artikel/mit-lm-sensors-und-rrd-cpu-und-mb-temperatur-uberwachen
# http://www.uvm.edu/~bcodding/ticker/archives/33
# http://blog.stefan-betz.net/2009/1/6/collectd-und-rrdtool-im-einsatz
# http://wiki.lugbz.de/HowTo/SelfMadeMonitoring
# https://jeremy.visser.name/2010/02/23/enable-caching-in-collectd
# https://collectd.org/wiki/index.php/Inside_the_RRDtool_plugin

# Testing:
# rrdtool info /var/lib/rrdcached/db/localhost/<xxx>/<xxx>.rrd

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_MKCONF_SCRIPTS_DIR=${ESB_MKCONF_SCRIPTS_DIR:-"/usr/share/enterprisestoragebox/mkconf"}
ESB_RRDCACHED_SOCKETFILE=${ESB_RRDCACHED_SOCKETFILE:-"/var/run/rrdcached.sock"}
ESB_RRDCACHED_BASEDIR=${ESB_RRDCACHED_BASEDIR:-"/var/lib/rrdcached/db/"}

ESB_COLLECTD_CONFIG=${ESB_COLLECTD_CONFIG:-"/etc/collectd/collectd.conf"}
ESB_COLLECTD_DEFAULT=${ESB_COLLECTD_DEFAULT:-"/etc/default/collectd"}
ESB_COLLECTD_CRON=${ESB_COLLECTD_CRON:-"/etc/cron.d/enterprisestoragebox-rrdtoolgraph"}
ESB_COLLECTD_PLUGINS_DIR=${ESB_COLLECTD_PLUGINS_DIR:-"${ESB_MKCONF_SCRIPTS_DIR}/collectd.d"}
ESB_COLLECTD_HOSTNAME=${ESB_COLLECTD_HOSTNAME:-"localhost"}
ESB_COLLECTD_FQDNLOOKUP=${ESB_COLLECTD_FQDNLOOKUP:-"true"}
ESB_COLLECTD_SYSLOG_LOGLEVEL=${ESB_COLLECTD_SYSLOG_LOGLEVEL:-"info"}
ESB_COLLECTD_RRDCACHED_CREATEFILES=${ESB_COLLECTD_RRDCACHED_CREATEFILES:-"true"}
ESB_COLLECTD_RRDCACHED_COLLECTSTATISTICS=${ESB_COLLECTD_RRDCACHED_COLLECTSTATISTICS:-"true"}
ESB_COLLECTD_RRDTOOL_MKGRAPH=${ESB_COLLECTD_RRDTOOL_MKGRAPH:-"/usr/sbin/esb-mkgraph"}
ESB_COLLECTD_RRDTOOL_MKGRAPH_INTERVAL=${ESB_COLLECTD_RRDTOOL_MKGRAPH_INTERVAL:-"15"}
ESB_COLLECTD_RRDTOOL_GRAPH_WIDTH=${ESB_COLLECTD_RRDTOOL_GRAPH_WIDTH:-"400"}
ESB_COLLECTD_RRDTOOL_GRAPH_HEIGHT=${ESB_COLLECTD_RRDTOOL_GRAPH_HEIGHT:-"120"}
ESB_COLLECTD_RRDTOOL_GRAPH_IMGFORMAT=${ESB_COLLECTD_RRDTOOL_GRAPH_IMGFORMAT:-"PNG"}
ESB_COLLECTD_RRDTOOL_GRAPH_IMGDIR=${ESB_COLLECTD_RRDTOOL_GRAPH_IMGDIR:-"/var/lib/enterprisestoragebox/rrd"}
ESB_COLLECTD_UNIXSOCK_SOCKETFILE=${ESB_COLLECTD_UNIXSOCK_SOCKETFILE:-"/var/run/collectd.socket"}
ESB_COLLECTD_UNIXSOCK_SOCKETGROUP=${ESB_COLLECTD_UNIXSOCK_SOCKETGROUP:-"root"}
ESB_COLLECTD_UNIXSOCK_SOCKETPERMS=${ESB_COLLECTD_UNIXSOCK_SOCKETPERMS:-"0660"}

mkconf() {
	# Create '/etc/collectd/collectd.conf' file
	cat <<EOF > ${ESB_COLLECTD_CONFIG}
Hostname "${ESB_COLLECTD_HOSTNAME}"
FQDNLookup ${ESB_COLLECTD_FQDNLOOKUP}

LoadPlugin syslog
<Plugin syslog>
  LogLevel ${ESB_COLLECTD_SYSLOG_LOGLEVEL}
</Plugin>

LoadPlugin rrdcached
<Plugin rrdcached>
	DaemonAddress "unix:${ESB_RRDCACHED_SOCKETFILE}"
	DataDir "${ESB_RRDCACHED_BASEDIR}"
	CreateFiles ${ESB_COLLECTD_RRDCACHED_CREATEFILES}
	CollectStatistics ${ESB_COLLECTD_RRDCACHED_COLLECTSTATISTICS}
</Plugin>

LoadPlugin unixsock
<Plugin unixsock>
  SocketFile "${ESB_COLLECTD_UNIXSOCK_SOCKETFILE}"
  SocketGroup "${ESB_COLLECTD_UNIXSOCK_SOCKETGROUP}"
  SocketPerms "${ESB_COLLECTD_UNIXSOCK_SOCKETPERMS}"
</Plugin>

EOF

	# Create '/etc/default/collectd' file
	cat <<EOF > ${ESB_COLLECTD_DEFAULT}
# /etc/default/collectd

# 0: start collectd on boot, 1: do not start collectd on boot
# default: 0
DISABLE=0

# 0: start collectd in stand-alone mode, 1: monitor collectd using collectdmon
# default: 1
USE_COLLECTDMON=0

# number of seconds to wait for collectd to shut down
# default: 30
MAXWAIT=30

# 0: do not enable core-files, 1: enable core-files ... if collectd crashes
# default: 0
ENABLE_COREFILES=0
EOF

	# Create '/etc/cron.d/collectd-rrdgraph' file. Take care about that there
	# will not be send an email if the cron job fails.
	cat <<EOF > ${ESB_COLLECTD_CRON}
# Create graphs every ${ESB_COLLECTD_RRDTOOL_MKGRAPH_INTERVAL} minutes
# m h dom mon dow user    command
*/${ESB_COLLECTD_RRDTOOL_MKGRAPH_INTERVAL} * * * * root ${ESB_COLLECTD_RRDTOOL_MKGRAPH} >/dev/null 2>&1
EOF

	# Check if the system performance statistics service is enabled.
	enabled=$(esb_config_get "//system/monitoring/perfstats")

	# Create '/usr/sbin/esb-mkgraph' file
	cat <<EOF > ${ESB_COLLECTD_RRDTOOL_MKGRAPH}
#!/bin/sh
# This script is auto-generated.
# WARNING: Do not edit this file, your changes will be lost.
set -e

DATA="${ESB_RRDCACHED_BASEDIR}/${ESB_COLLECTD_HOSTNAME}"
IMGDIR="${ESB_COLLECTD_RRDTOOL_GRAPH_IMGDIR}"
HOURSTART="-1h"
HOURTITLE=" - by hour"
DAYSTART="-1d"
DAYTITLE=" - by day"
WEEKSTART="-1w"
WEEKTITLE=" - by week"
MONTHSTART="-1m"
MONTHTITLE=" - by month"
YEARSTART="-1y"
YEARTITLE=" - by year"
DEFAULTS="--daemon unix:${ESB_RRDCACHED_SOCKETFILE} --imgformat ${ESB_COLLECTD_RRDTOOL_GRAPH_IMGFORMAT} --width ${ESB_COLLECTD_RRDTOOL_GRAPH_WIDTH} --height ${ESB_COLLECTD_RRDTOOL_GRAPH_HEIGHT} --alt-y-grid --interlaced --font TITLE:9:."
LASTUPDATE="Last update\: \$(date | sed -e 's/:/\\\:/g')\r"

# Helper function to copy the error graph image
esb_copy_error_rrd_graph_image() {
	for period in hour day week month year; do
		cp ${ESB_RRDGRAPH_ERROR_IMAGE} \${IMGDIR}/\$1-\${period}.png
	done
}

# Exit here if the rrdtool service is disabled.
[ 0 -eq ${enabled} ] && exit 0
# Flush all rrdtool data
echo "FLUSHALL" | socat - unix:${ESB_RRDCACHED_SOCKETFILE} >/dev/null
# Create target graph directory
mkdir -p \${IMGDIR}
# Remove old graphs
rm -f \${IMGDIR}/*

EOF

	chmod 755 ${ESB_COLLECTD_RRDTOOL_MKGRAPH}

	# Process the collectd plugins.
	run-parts --exit-on-error ${ESB_COLLECTD_PLUGINS_DIR}

	cat <<EOF >> ${ESB_COLLECTD_CONFIG}
Include "/etc/collectd/thresholds.conf"
EOF
}

case "$1" in
	mkconf|*)
		mkconf
		;;
esac
