#!/bin/bash
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox

ESB_MKCONF_SCRIPTS_DIR=${ESB_MKCONF_SCRIPTS_DIR:-"/usr/share/enterprisestoragebox/mkconf"}

ESB_FSTAB_CONFIG=${ESB_FSTAB_CONFIG:-"/etc/fstab"}
ESB_FSTAB_SECTIONNAME=${ESB_FSTAB_SECTIONNAME:-"enterprisestoragebox"}
ESB_FSTAB_EXTENSIONS_DIR=${ESB_FSTAB_EXTENSIONS_DIR:-"${ESB_MKCONF_SCRIPTS_DIR}/fstab.d"}

# Execute all scripts building the custom fstab configuration.
fstabcfg=$(echo -n "# >>> [${ESB_FSTAB_SECTIONNAME}]\n"; run-parts --exit-on-error ${ESB_FSTAB_EXTENSIONS_DIR} | perl -p -e 's/\n/\\n/g'; echo -n "# <<< [${ESB_FSTAB_SECTIONNAME}]")

# Append custom fstab configuration if not still present or replace existing one.
if ! grep -E "^# >>> \[${ESB_FSTAB_SECTIONNAME}\]\s*$" ${ESB_FSTAB_CONFIG} >/dev/null; then
	echo -e "${fstabcfg}" >> ${ESB_FSTAB_CONFIG}
else
	sed -i "/# >>> \[${ESB_FSTAB_SECTIONNAME}\]/,/# <<< \[${ESB_FSTAB_SECTIONNAME}\]/ c ${fstabcfg}" ${ESB_FSTAB_CONFIG}
fi
