#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://www.vdr-wiki.de/wiki/index.php/Debian_-_WAKE_ON_LAN
# http://www.brueck-computer.de/index2.php?modul=1404&link=1

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_HALT_DEFAULT=${ESB_HALT_DEFAULT:-"/etc/default/halt"}
ESB_HALT_HALT=${ESB_HALT_HALT:-"poweroff"}
ESB_HALT_NETDOWN=${ESB_HALT_NETDOWN:-"no"}

mkconf() {
	# Create '/etc/default/halt' file
	cat <<EOF > ${ESB_HALT_DEFAULT}
# Default behaviour of shutdown -h / halt. Set to "halt" or "poweroff".
HALT=${ESB_HALT_HALT}
EOF

	xmlstarlet sel -t \
	  -i "count(//system/network/interfaces/interface[wol='1']) > 0" \
		-n -o "# Do not shut down network interfaces, needed to use wake-on-lan" -n \
		-o "NETDOWN=${ESB_HALT_NETDOWN}" -n \
	  -b  \
	  ${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_HALT_DEFAULT}
}

case "$1" in
	mkconf|*)
		mkconf
		;;
esac
