#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_MKCONF_SCRIPTS_DIR=${ESB_MKCONF_SCRIPTS_DIR:-"/usr/share/enterprisestoragebox/mkconf"}

ESB_INTERFACES_EXTENSIONS_DIR=${ESB_INTERFACES_EXTENSIONS_DIR:-"${ESB_MKCONF_SCRIPTS_DIR}/interfaces.d"}
ESB_INTERFACES_CONFIG=${ESB_INTERFACES_CONFIG:-"/etc/network/interfaces"}

# Build the configuration file.
cat /dev/null > ${ESB_INTERFACES_CONFIG}
run-parts --exit-on-error ${ESB_INTERFACES_EXTENSIONS_DIR}
