#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# https://raid.wiki.kernel.org/index.php/RAID_setup
# http://en.wikipedia.org/wiki/Mdadm
# http://old-de.opensuse.org/SW-RAID_und_LVM_(Grundlagen)
# http://www.felipe1982.com/blog/2010/01/27/software-raid-5-on-gnulinux-using-mdadm-in-6-easy-steps

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_MDADM_DEFAULT=${ESB_MDADM_DEFAULT:-"/etc/default/mdadm"}
ESB_MDADM_CONFIG=${ESB_MDADM_CONFIG:-"/etc/mdadm/mdadm.conf"}
ESB_MDADM_AUTOSTART=${ESB_MDADM_AUTOSTART:-"true"}
ESB_MDADM_AUTOCHECK=${ESB_MDADM_AUTOCHECK:-"true"}
ESB_MDADM_STARTDAEMON=${ESB_MDADM_STARTDAEMON:-"true"}
ESB_MDADM_DAEMONOPTIONS=${ESB_MDADM_DAEMONOPTIONS:-"--syslog"}
ESB_MDADM_VERBOSE=${ESB_MDADM_VERBOSE:-"false"}
ESB_MDADM_MAILFROM=${ESB_MDADM_MAILFROM:-"root"}

# Create the '/etc/default/mdadm' file.
cat > ${ESB_MDADM_DEFAULT} <<EOF
# INITRDSTART:
#   list of arrays (or 'all') to start automatically when the initial ramdisk
#   loads. This list *must* include the array holding your root filesystem. Use
#   'none' to prevent any array from being started from the initial ramdisk.
#INITRDSTART='none'

# AUTOSTART:
#   should mdadm start arrays listed in /etc/mdadm/mdadm.conf automatically
#   during boot?
AUTOSTART=${ESB_MDADM_AUTOSTART}

# AUTOCHECK:
#   should mdadm run periodic redundancy checks over your arrays? See
#   /etc/cron.d/mdadm.
AUTOCHECK=${ESB_MDADM_AUTOCHECK}

# START_DAEMON:
#   should mdadm start the MD monitoring daemon during boot?
START_DAEMON=${ESB_MDADM_STARTDAEMON}

# DAEMON_OPTIONS:
#   additional options to pass to the daemon.
DAEMON_OPTIONS="${ESB_MDADM_DAEMONOPTIONS}"

# VERBOSE:
#   if this variable is set to true, mdadm will be a little more verbose e.g.
#   when creating the initramfs.
VERBOSE=${ESB_MDADM_VERBOSE}
EOF

# Create the '/etc/mdadm/mdadm.conf' file.
cat > ${ESB_MDADM_CONFIG} <<EOF
# mdadm.conf
#
# Please refer to mdadm.conf(5) for information about this file.
#

# by default, scan all partitions (/proc/partitions) for MD superblocks.
# alternatively, specify devices to scan, using wildcards if desired.
# Note, if no DEVICE line is present, then "DEVICE partitions" is assumed.
# To avoid the auto-assembly of RAID devices a pattern that CAN'T match is
# used if no RAID devices are configured.
DEVICE partitions

# auto-create devices with Debian standard permissions
CREATE owner=root group=disk mode=0660 auto=yes

# automatically tag new arrays as belonging to the local system
HOMEHOST <system>

# definitions of existing MD arrays
EOF

# Append definition of existing arrays.
mdadm --detail --scan >> ${ESB_MDADM_CONFIG}

# Set email configuration.
xmlstarlet sel -t -m "//system/email" \
  -i "enable[. = '1'] and //system/notification/notifications/mdadm[. = '1']" \
	-n \
	-o "# instruct the monitoring daemon where to send mail alerts" -n \
	-v "concat('MAILADDR ',primaryemail)" -n \
	-o "MAILFROM ${ESB_MDADM_MAILFROM}" \
  -b \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_MDADM_CONFIG}

# Update initramfs.
# Note, on various platforms the initramfs-tools package
# is not installed.
if [ -x "/usr/sbin/update-initramfs" ]; then
	rm -f /var/lib/mdadm/CONF-UNCHECKED
	update-initramfs -u -k all
fi
