#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://mmonit.com/monit/documentation/monit.html
# http://mmonit.com/wiki/Monit/ConfigurationExamples
# http://www.cyberciti.biz/tips/howto-monitor-and-restart-linux-unix-service.html
# https://www.adminlife.net/allgemein/howto-monit-unter-debian-etch
# http://www.howtoforge.com/server_monitoring_monit_munin
# http://www.howtoforge.de/howto/server-uberwachung-mit-munin-und-monit
# http://www.howtoforge.de/howto/wie-man-sich-mit-monit-per-sms-warnen-lasst-bei-einem-serverabsturz
# http://www.musicinfo.org/node/81
# http://www.cyberciti.biz/faq/tag/etcinitdmonit
# http://www.tim-bormann.de/linux-dienste-berwachen-mit-monit
# http://en.gentoo-wiki.com/wiki/Monit
# http://www.debianadmin.com/monitoring-debian-servers-using-monit.html
# http://www.uibk.ac.at/zid/systeme/linux/monit.html
# http://wiki.ubuntuusers.de/Monit
# http://viktorpetersson.com/2010/07/09/setting-up-monit-to-monitor-apache-and-postgresql-on-ubuntu

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_MKCONF_SCRIPTS_DIR=${ESB_MKCONF_SCRIPTS_DIR:-"/usr/share/enterprisestoragebox/mkconf"}

ESB_MONIT_CONFIG=${ESB_MONIT_CONFIG:-"/etc/monit/monitrc"}
ESB_MONIT_CONFIG_INCLUDE_DIR=${ESB_MONIT_CONFIG_INCLUDE_DIR:-"/etc/monit/conf.d"}
ESB_MONIT_DEFAULT=${ESB_MONIT_DEFAULT:-"/etc/default/monit"}
ESB_MONIT_CHECK_INTERVAL=${ESB_MONIT_CHECK_INTERVAL:-"30"}
ESB_MONIT_LOGFILE=${ESB_MONIT_LOGFILE:-"syslog facility log_daemon"}
ESB_MONIT_IDFILE=${ESB_MONIT_IDFILE:-"/var/lib/monit/id"}
ESB_MONIT_STATEFILE=${ESB_MONIT_STATEFILE:-"/var/lib/monit/state"}
ESB_MONIT_PORT=${ESB_MONIT_PORT:-"2812"}
ESB_MONIT_EVENTQUEUE_BASEDIR=${ESB_MONIT_EVENTQUEUE_BASEDIR:-"/var/lib/monit/events"}
ESB_MONIT_EVENTQUEUE_SLOTS=${ESB_MONIT_EVENTQUEUE_SLOTS:-"100"}
ESB_MONIT_EMAIL_ALERT_NOTEVENTS=${ESB_MONIT_EMAIL_ALERT_NOTEVENTS:-"action, instance"}
ESB_MONIT_EMAIL_TIMEOUT=${ESB_MONIT_EMAIL_TIMEOUT:-"5"}
ESB_MONIT_EXTENSIONS_DIR=${ESB_MONIT_EXTENSIONS_DIR:-"${ESB_MKCONF_SCRIPTS_DIR}/monit.d"}
ESB_MONIT_DELAY_SECONDS=${ESB_MONIT_DELAY_SECONDS:-"30"}

# Make sure used directories exists
mkdir -p ${ESB_MONIT_EVENTQUEUE_BASEDIR}

# /etc/default/monit
cat > ${ESB_MONIT_DEFAULT} <<EOF
# You must set this variable to yes for monit to start
START=yes
EOF

# /etc/monit/monitrc
cat > ${ESB_MONIT_CONFIG} <<EOF
set daemon ${ESB_MONIT_CHECK_INTERVAL} with start delay ${ESB_MONIT_DELAY_SECONDS}
set logfile ${ESB_MONIT_LOGFILE}
set idfile ${ESB_MONIT_IDFILE}
set statefile ${ESB_MONIT_STATEFILE}
set httpd port ${ESB_MONIT_PORT} and
  use address localhost  # only accept connection from localhost
  allow localhost        # allow localhost to connect to the server and
# allow admin:monit      # require user 'admin' with password 'monit'
set eventqueue
  basedir ${ESB_MONIT_EVENTQUEUE_BASEDIR}
  slots ${ESB_MONIT_EVENTQUEUE_SLOTS}

EOF

xmlstarlet sel -t -m "//system/email" \
  -i "enable = '1'" \
	-o "set mailserver 127.0.0.1" \
	-o "  with timeout ${ESB_MONIT_EMAIL_TIMEOUT} seconds" -n \
	-v "concat('set mail-format { from: ',sender,' }')" -n \
	-v "concat('set alert ',primaryemail,' but not on { ${ESB_MONIT_EMAIL_ALERT_NOTEVENTS} }')" -n \
  -b \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_MONIT_CONFIG}

# Create the service configuration files.
rm -f ${ESB_MONIT_CONFIG_INCLUDE_DIR}/enterprisestoragebox-*.conf
run-parts --exit-on-error ${ESB_MONIT_EXTENSIONS_DIR}
find ${ESB_MONIT_CONFIG_INCLUDE_DIR} -type f -print0 | xargs -0r chmod 0600

# Include custom config files.
cat <<EOF >> ${ESB_MONIT_CONFIG}
include ${ESB_MONIT_CONFIG_INCLUDE_DIR}/*
EOF
