#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Testing:
# ntpq -p
# ntpd -gq

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_NTP_CONFIG=${ESB_NTP_CONFIG:-"/etc/ntp.conf"}

xmlstarlet sel -t \
  -o "# /etc/ntp.conf, configuration for ntpd; see ntp.conf(5) for help" -n \
  -n \
  -o "driftfile /var/lib/ntp/ntp.drift" -n \
  -n \
  -o "# Disable the panic feature." -n \
  -o "tinker panic 0" -n \
  -n \
  -o "statistics loopstats peerstats clockstats" -n \
  -o "filegen loopstats file loopstats type day enable" -n \
  -o "filegen peerstats file peerstats type day enable" -n \
  -o "filegen clockstats file clockstats type day enable" -n \
  -n \
  -o "server 127.127.1.0 # Local clock" -n \
  -o "fudge 127.127.1.0 stratum 12" -n \
  -v "concat('server ',//system/time/ntp/timeservers,' iburst')" -n \
  -n \
  -o "# By default, exchange time with everybody, but do not allow configuration." -n \
  -o "restrict -4 default kod notrap nomodify nopeer noquery" -n \
  -o "restrict -6 default kod notrap nomodify nopeer noquery" -n \
  -n \
  -o "# Local users may interrogate the ntp server more closely." -n \
  -o "restrict 127.0.0.1" -n \
  -o "restrict ::1" \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc > ${ESB_NTP_CONFIG}

chmod 644 ${ESB_NTP_CONFIG}
