#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_MONIT_SERVICE_FILESYSTEM_CONFIG=${ESB_MONIT_SERVICE_FILESYSTEM_CONFIG:-"/etc/monit/conf.d/enterprisestoragebox-filesystem.conf"}
ESB_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE=${ESB_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE:-"80"}

if [ "$(esb_config_get "//system/notification/notifications/monitfilesystems")" = "1" ]; then
	# Monitor root filesystem.
	cat <<EOF > ${ESB_MONIT_SERVICE_FILESYSTEM_CONFIG}
# Alert if disk space of root filesystem gets low
check filesystem rootfs with path /
  if space usage > ${ESB_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE}% for 5 times within 15 cycles
    then alert else if succeeded for 10 cycles then alert

EOF

	# Monitor mounted filesystems.
	xmlstarlet sel -t \
	  -m "//system/fstab/mntent[not(contains(opts,'bind') or contains(opts,'loop'))]" \
		-v uuid \
		-i "position() != last()" -n -b \
	  -b \
	  ${ESB_CONFIG_FILE} | xmlstarlet unesc |
	  while read uuid; do
		  # Get the mount point of the filesystem.
		  dir=$(esb_config_get "//system/fstab/mntent[uuid='${uuid}']/dir")
		  # Generate a unique identifier.
		  fscheckname=$(echo "fs${dir}" | tr "/ " "_")
		  progcheckname=$(echo "mp${dir}" | tr "/ " "_")
		  # Note, do not monitor the filesystem space usage for various
		  # types like ISO9660 and UDF because for those filesystems the
		  # usage is always reported as 100% by the 'df' command.
		  xmlstarlet sel -t -m "//system/fstab/mntent[uuid='${uuid}']" \
		    -o "check filesystem ${fscheckname} with path \"${dir}\"" -n \
			-i "type[.!='iso9660' and .!='udf']" \
			  -o "  if space usage > ${ESB_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE}% for 5 times within 15 cycles" -n \
			  -o "    then alert else if succeeded for 10 cycles then alert" -n \
			-b \
			-o "  #check program ${progcheckname} with path \"/bin/mountpoint -q '${dir}'\"" -n \
			-o "  #  if status == 1 then alert" -n \
			${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_MONIT_SERVICE_FILESYSTEM_CONFIG}
	  done
fi
