#!/bin/sh
#
# This file is part of EnterpriseStorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
#
# EnterpriseStorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriseStorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriseStorageBox. If not, see <http://www.gnu.org/licenses/>.

_esb-sysinfo()
{
	local cur prev

	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	# Directory where the ESB-sysinfo modules are stored.
	ESB_SYSINFO_MODULES="/usr/share/enterprisestoragebox/sysinfo/modules.d"

	# If previous word is "-c" (category) then print out only numbers.
	case $prev in
	-c)  
		COMPREPLY=( $( command ls --color=never $ESB_SYSINFO_MODULES \
		  2>/dev/null | egrep '^[0-9]{2}-' | sed 's/[a-z\-]*$//g') )
		COMPREPLY=( $( compgen -W '${COMPREPLY[@]#$ESB_SYSINFO_MODULES}' \
		  -- "$cur" ) )
		;;
	*)
		# If the user types "-" print out the CLI arguments.
		if [[ "$cur" == -* ]]; then
			COMPREPLY=( $( compgen -W '-c -l -h' -- "$cur" ) )
		else
			# Print out all the modules in $ESB_SYSINFO_MODULES starting
			# with 2 digits and a dash "-".
			COMPREPLY=( $( command ls --color=never $ESB_SYSINFO_MODULES \
			  2>/dev/null | egrep '^[0-9]{2}-') )
			COMPREPLY=( $( compgen -W '${COMPREPLY[@]#$ESB_SYSINFO_MODULES}' \
			  -- "$cur" ) )
		fi
	esac
} &&
complete -F _esb-sysinfo esb-sysinfo
