#!/bin/sh
#
# This file is part of EnterpriseStorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriseStorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriseStorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriseStorageBox. If not, see <http://www.gnu.org/licenses/>.

. /usr/share/debconf/confmodule

set -e

logger -t finish-install "Configure system environment"

db_progress START 0 2 enterprisestoragebox-installer/finish-install/progress/title

# Regenerate SSH key for user 'root'. It was created during the build
# process of the ISO image.
db_progress INFO enterprisestoragebox-installer/finish-install/progress/info/ssh_keygen
in-target rm -f /root/.ssh/id_rsa
in-target rm -f /root/.ssh/id_rsa.pub
in-target ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ''

# Syncronize database with system configuration.
db_progress STEP 1
db_progress INFO enterprisestoragebox-installer/finish-install/progress/info/init_database
in-target esb-initsystem

db_progress STOP

exit 0
