#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_PROFTPD_CONFIG=${ESB_PROFTPD_CONFIG:-"/etc/proftpd/proftpd.conf"}
ESB_PROFTPD_DISPLAYLOGIN=${ESB_PROFTPD_DISPLAYLOGIN:-"/srv/ftp/welcome.msg"}
ESB_PROFTPD_SHOW_DISPLAYLOGIN=${ESB_PROFTPD_SHOW_DISPLAYLOGIN:-"yes"}

# Create welcome message file.
displaylogin=$(esb_config_get "//services/ftp/displaylogin")
if [ -z "${displaylogin}" ]; then
	cat <<EOF > ${ESB_PROFTPD_DISPLAYLOGIN}
Welcome user %U@%R to %L FTP server.
The local time is: %T
EOF
else
	echo ${displaylogin} > ${ESB_PROFTPD_DISPLAYLOGIN}
fi

# Display the welcome message at login?
if esb_checkyesno "${ESB_PROFTPD_SHOW_DISPLAYLOGIN}"; then
	cat >> ${ESB_PROFTPD_CONFIG} <<EOF
DisplayLogin ${ESB_PROFTPD_DISPLAYLOGIN}
EOF
fi
