#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://wiki.ubuntuusers.de/ProFTPD
# http://www.proftpd.de/HowTo-Server-Config.42.0.html
# http://wiki.ubuntu-forum.de/index.php/ProFTPd

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_SSL_CERTIFICATE_DIR=${ESB_SSL_CERTIFICATE_DIR:-"/etc/ssl"}
ESB_SSL_CERTIFICATE_PREFIX=${ESB_SSL_CERTIFICATE_PREFIX:-"enterprisestoragebox-"}

ESB_PROFTPD_MODTLS_CONFIG=${ESB_PROFTPD_MODTLS_CONFIG:-"/etc/proftpd/tls.conf"}
ESB_PROFTPD_MODTLS_TLSLOG=${ESB_PROFTPD_MODTLS_TLSLOG:-"/var/log/proftpd/tls.log"}
ESB_PROFTPD_MODTLS_TLSPROTOCOL=${ESB_PROFTPD_MODTLS_TLSPROTOCOL:-"TLSv1"}
ESB_PROFTPD_MODTLS_TLSVERIFYCLIENT=${ESB_PROFTPD_MODTLS_TLSVERIFYCLIENT:-"off"}
ESB_PROFTPD_MODTLS_TLSRENEGOTIATE=${ESB_PROFTPD_MODTLS_TLSRENEGOTIATE:-"required off"}

# Create SSL/TLS certificates and configuration file
# Create a SSL certificate:
# openssl req -new -x509 -days 365 -nodes -out /etc/ssl/certs/proftpd.crt -keyout /etc/ssl/private/proftpd.key
xmlstarlet sel -t -m "//services/ftp/modules/mod_tls" \
  -o "<IfModule mod_tls.c>" -n \
  -i "enable[. = '0']" -o "  TLSEngine off" -n -b \
  -i "enable[. = '1']" -o "  TLSEngine on" -n -b \
  -o "  TLSLog ${ESB_PROFTPD_MODTLS_TLSLOG}" -n \
  -o "  TLSProtocol ${ESB_PROFTPD_MODTLS_TLSPROTOCOL}" -n \
  -i "nocertrequest[. = '1'] | nosessionreuserequired[. = '1'] | useimplicitssl[. = '1']" \
	  -o "  TLSOptions " \
	  -i "nocertrequest[. = '1']" -o "NoCertRequest " -b \
	  -i "nosessionreuserequired[. = '1']" -o "NoSessionReuseRequired " -b \
	  -i "useimplicitssl[. = '1']" -o "UseImplicitSSL " -b \
	  -n \
  -b \
  -v "concat('  TLSRSACertificateFile ${ESB_SSL_CERTIFICATE_DIR}/certs/${ESB_SSL_CERTIFICATE_PREFIX}',sslcertificateref,'.crt')" -n \
  -v "concat('  TLSRSACertificateKeyFile ${ESB_SSL_CERTIFICATE_DIR}/private/${ESB_SSL_CERTIFICATE_PREFIX}',sslcertificateref,'.key')" -n \
  -o "  TLSVerifyClient ${ESB_PROFTPD_MODTLS_TLSVERIFYCLIENT}" -n \
  -o "  TLSRenegotiate ${ESB_PROFTPD_MODTLS_TLSRENEGOTIATE}" -n \
  -i "required[. = '0']" -o "  TLSRequired off" -n -b \
  -i "required[. = '1']" -o "  TLSRequired on" -n -b \
  -i "string-length(extraoptions) > 0" -v extraoptions -n -b \
  -o "</ifModule>" \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc > ${ESB_PROFTPD_MODTLS_CONFIG}
