#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://wiki.ubuntuusers.de/ProFTPD
# http://www.proftpd.de/HowTo-Server-Config.42.0.html
# http://wiki.ubuntu-forum.de/index.php/ProFTPd

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_PROFTPD_CONFIG=${ESB_PROFTPD_CONFIG:-"/etc/proftpd/proftpd.conf"}
ESB_PROFTPD_MODBAN_BANCONTROLSACLS=${ESB_PROFTPD_MODBAN_BANCONTROLSACLS:-"all allow user root"}
ESB_PROFTPD_MODBAN_BANLOG=${ESB_PROFTPD_MODBAN_BANLOG:-"/var/log/proftpd/ban.log"}
ESB_PROFTPD_MODBAN_BANMESSAGE=${ESB_PROFTPD_MODBAN_BANMESSAGE:-"Host %a has been banned"}
ESB_PROFTPD_MODBAN_BANTABLE=${ESB_PROFTPD_MODBAN_BANTABLE:-"/var/run/proftpd/ban.tab"}

xmlstarlet sel -t -m "//services/ftp" \
	  -o "<IfModule mod_ban.c>" -n \
	  -i "count(modules/mod_ban/rule) = 0" -o "  BanEngine off" -n -b \
	  -i "count(modules/mod_ban/rule) > 0" -o "  BanEngine on" -n -b \
	  -o "  BanControlsACLs ${ESB_PROFTPD_MODBAN_BANCONTROLSACLS}" -n \
	  -o "  BanLog ${ESB_PROFTPD_MODBAN_BANLOG}" -n \
	  -o "  BanMessage ${ESB_PROFTPD_MODBAN_BANMESSAGE}" -n \
	  -m "modules/mod_ban/rule" \
		  -v "concat('  BanOnEvent ',event,' ',occurrence,'/',timeinterval,' ',expire)" -n \
	  -b \
	  -o "  BanTable ${ESB_PROFTPD_MODBAN_BANTABLE}" -n \
	  -o "</ifModule>" -n \
  -b \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_PROFTPD_CONFIG}
