#!/bin/sh
#
# This file is part of EnterpriseStorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriseStorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriseStorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriseStorageBox. If not, see <http://www.gnu.org/licenses/>.

set -eu

MDADM=/sbin/mdadm
[ -x "$MDADM" ] || exit 0

# Exit if no email address is configured, otherwise the error message
# 'mdadm: No mail address or alert command - not monitoring.' will be
# displayed.
[ -z "$(grep "^MAILADDR" /etc/mdadm/mdadm.conf)" ] && exit 0

exec $MDADM --monitor --scan --oneshot
