#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://de.linwiki.org/wiki/Linuxfibel_-_Netzwerk_Server_-_NFS_Server
# http://wiki.ubuntuusers.de/NFS
# http://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-nfs-server-config-exports.html
# https://help.ubuntu.com/community/NFSv4Howto
# http://jkossen.nl/2009/05/12/simple-nfsv4-configuration-for-debian-and-ubuntu.html
# http://doc.opensuse.org/products/opensuse/openSUSE/opensuse-reference/cha.nfs.html

# Testing:
# showmount -e <nfs-server>

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_NFSD_CONFIG=${ESB_NFSD_CONFIG:-"/etc/exports"}
ESB_NFSD_EXPORT_DIR=${ESB_NFSD_EXPORT_DIR:-"/export"}
ESB_NFSD_DEFAULT_EXPORT_OPTIONS=${ESB_NFSD_DEFAULT_EXPORT_OPTIONS:-""}
ESB_NFSD_V4_ENABLE=${ESB_NFSD_V4_ENABLE:-"yes"}
ESB_NFSD_V4_DEFAULT_EXPORT_OPTIONS=${ESB_NFSD_V4_DEFAULT_EXPORT_OPTIONS:-"ro,fsid=0,root_squash,no_subtree_check,hide"}

# Create /etc/exports file.
cat <<EOF > ${ESB_NFSD_CONFIG}
# /etc/exports: the access control list for filesystems which may be exported
#               to NFS clients.  See exports(5).
EOF

xmlstarlet sel -t \
  -m "//services/nfs/shares/share" \
	-o "${ESB_NFSD_EXPORT_DIR}/" ${ESB_XMLSTARLET_GET_SHAREDFOLDER_NAME} \
	-v "concat(' ',normalize-space(client),'(',options)" \
	-i "string-length(extraoptions) > 0" \
	  -v "concat(',',extraoptions)" \
	-b \
    -i "string-length('${ESB_NFSD_DEFAULT_EXPORT_OPTIONS}') > 0" \
	  -v "concat(',','${ESB_NFSD_DEFAULT_EXPORT_OPTIONS}')" \
	-b \
	-o ")" \
	-i "position() != last()" -n -b \
  -b \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_NFSD_CONFIG}

if esb_checkyesno "${ESB_NFSD_V4_ENABLE}"; then
	# Export duplicate shares only once (emulate SQL 'DISTINCT' to filter
	# duplicates).
	xmlstarlet sel -t \
		-n \
		-o "# NFSv4 - pseudo filesystem root" -n \
		-m "//services/nfs/shares/share[not(client=preceding-sibling::*/client)]" \
		  -v "concat('${ESB_NFSD_EXPORT_DIR} ',normalize-space(client),'(${ESB_NFSD_V4_DEFAULT_EXPORT_OPTIONS})')" \
		  -i "position() != last()" -n -b \
		-b \
	  -b \
	  ${ESB_CONFIG_FILE} | xmlstarlet unesc >> ${ESB_NFSD_CONFIG}
fi
