#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /usr/share/enterprisestoragebox/sysinfo/functions

esb_sysinfo_begin_msg "Configured APT data sources"
esb_sysinfo_msg_caption "/etc/apt/sources.list"
esb_sysinfo_msg </etc/apt/sources.list
esb_sysinfo_msg_separator
esb_sysinfo_msg_caption "/etc/apt/sources.list.d"
ls -alh /etc/apt/sources.list.d | esb_sysinfo_msg
esb_sysinfo_msg_separator
for path in $(find /etc/apt/sources.list.d -maxdepth 1 -iname "*.list" -type f) ; do
	esb_sysinfo_msg_caption "${path}"
	esb_sysinfo_msg <"${path}"
done
esb_sysinfo_end_msg

exit 0
