#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_SSL_CERTIFICATE_DIR=${ESB_SSL_CERTIFICATE_DIR:-"/etc/ssl"}
ESB_SSL_CERTIFICATE_PREFIX=${ESB_SSL_CERTIFICATE_PREFIX:-"enterprisestoragebox-"}

# Remove all certificate files.
find "${ESB_SSL_CERTIFICATE_DIR}/certs" -type f -iname "${ESB_SSL_CERTIFICATE_PREFIX}*.crt" -print0 | xargs -0r rm -f
find "${ESB_SSL_CERTIFICATE_DIR}/private" -type f -iname "${ESB_SSL_CERTIFICATE_PREFIX}*.key" -print0 | xargs -0r rm -f

# Create the certificate files.
xmlstarlet sel -t -m "//system/certificates/sslcertificate" \
  -v uuid -i "position() != last()" -n -b \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc |
  while read uuid; do
	  crtfile="${ESB_SSL_CERTIFICATE_DIR}/certs/${ESB_SSL_CERTIFICATE_PREFIX}${uuid}.crt"
	  xmlstarlet sel -t -m "//system/certificates/sslcertificate[uuid='${uuid}']" \
		-v certificate \
		${ESB_CONFIG_FILE} | xmlstarlet unesc >"${crtfile}"
	  chmod 0640 "${crtfile}"

	  keyfile="${ESB_SSL_CERTIFICATE_DIR}/private/${ESB_SSL_CERTIFICATE_PREFIX}${uuid}.key"
	  xmlstarlet sel -t -m "//system/certificates/sslcertificate[uuid='${uuid}']" \
		-v privatekey \
		${ESB_CONFIG_FILE} | xmlstarlet unesc >"${keyfile}"
	  chmod 0600 "${keyfile}"
  done

# Create symbolic links to files named by the hash values
update-ca-certificates --fresh
