#!/bin/sh
#
# This file is part of EnterpriSestorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author   Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriSestorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriSestorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriSestorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox
. /usr/share/enterprisestoragebox/scripts/helper-functions

ESB_SSH_KEYS_DIR=${ESB_SSH_KEYS_DIR:-"/var/lib/enterprisestoragebox/ssh/keys"}
ESB_SSH_KEY_PREFIX=${ESB_SSH_KEY_PREFIX:-"enterprisestoragebox-"}

# Remove all certificate files.
find "${ESB_SSH_KEYS_DIR}" -type f -iname "${ESB_SSH_KEY_PREFIX}*" -print0 | xargs -0r rm -f

# Create the certificate files.
xmlstarlet sel -t -m "//system/certificates/sshcertificate" \
  -v uuid -i "position() != last()" -n -b \
  ${ESB_CONFIG_FILE} | xmlstarlet unesc |
  while read uuid; do
	  privkeyfile="${ESB_SSH_KEYS_DIR}/${ESB_SSH_KEY_PREFIX}${uuid}"
	  xmlstarlet sel -t -m "//system/certificates/sshcertificate[uuid='${uuid}']" \
		-v privatekey \
		${ESB_CONFIG_FILE} | xmlstarlet unesc >"${privkeyfile}"
	  chmod 0600 "${privkeyfile}"

      pubkeyfile="${ESB_SSH_KEYS_DIR}/${ESB_SSH_KEY_PREFIX}${uuid}.pub"
	  xmlstarlet sel -t -m "//system/certificates/sshcertificate[uuid='${uuid}']" \
		-v publickey \
		${ESB_CONFIG_FILE} | xmlstarlet unesc >"${pubkeyfile}"
	  chmod 0600 "${pubkeyfile}"
  done
