#!/bin/sh
#
# This file is part of EnterpriseStorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriseStorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriseStorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriseStorageBox. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/enterprisestoragebox

ESB_INITSYSTEM_SCRIPTS_DIR=${ESB_INITSYSTEM_SCRIPTS_DIR:-"/usr/share/enterprisestoragebox/initsystem"}

# Run all system initialization scripts.
if test $# -gt 0; then
	# Execute only given scripts.
	for name in $@; do
		${ESB_INITSYSTEM_SCRIPTS_DIR}/${name} 2>&1 >${ESB_LOG_DIR}/initsystem.log
	done
else
	# Execute all scripts.
	run-parts --exit-on-error ${ESB_INITSYSTEM_SCRIPTS_DIR} 2>&1 >${ESB_LOG_DIR}/initsystem.log
fi

# Remove the flag.
rm -f ${ESB_INITSYSTEM_FILE}

exit 0
