#!/bin/sh
#
# This file is part of EnterpriseStorageBox.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Artur Osinski-Stachowicz <artio0610@gmail.com>
# @copyright Copyright (c) 2009-2015 Artur Osinski-Stachowicz
#
# EnterpriseStorageBox is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# EnterpriseStorageBox is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EnterpriseStorageBox. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://wiki.rpath.com/wiki/Appliance:etcissueInitScript
# http://offbytwo.com/2008/05/09/show-ip-address-of-vm-as-console-pre-login-message.html

set -e

. /etc/default/enterprisestoragebox

if [ "$IFACE" = "lo" ]; then
	exit 0
fi
if [ "$ADDRFAM" != "inet" ] && [ "$ADDRFAM" != "inet6" ]; then
	exit 0
fi

esb-mkconf issue
